name: Deno Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build
      
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "bargpt"
          entrypoint: "./src/index.ts"
